"""Per-symbol transaction-cost lookup, backed by ``costs.yml``.

``vbt.yml`` carries a single global ``slippage: 0.0001`` for every
symbol. That flat 1 bp is generous on EUR-USD (empirical half spread
≈ 0.5 bp) and stingy on the wider crosses. ``costs.yml`` — generated by
``scripts/build_cost_table.py`` from the MT5 broker spreads — holds the
per-symbol figures, and this module is the read-only accessor:

    from framework.costs import cost_for

    slippage = cost_for("EUR-USD")          # half spread, per fill
    stress   = cost_for("EUR-USD", stat="spread_frac_p75")

The file is parsed once per path via ``lru_cache``; call
``load_cost_table.cache_clear()`` after regenerating it in the same
process (tests do).
"""

from __future__ import annotations

import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

PROJECT_ROOT: Path = Path(__file__).resolve().parents[2]

_COSTS_FILE: Path = PROJECT_ROOT / "costs.yml"

_REGEN_HINT = "run `python scripts/build_cost_table.py` to (re)generate it"


@lru_cache(maxsize=None)
def load_cost_table(path: str | Path | None = None) -> dict[str, dict[str, Any]]:
    """Return the parsed ``costs.yml`` mapping ``symbol -> stats``.

    ``path`` defaults to ``costs.yml`` at the project root.
    """
    resolved = Path(path) if path is not None else _COSTS_FILE
    if not resolved.exists():
        raise FileNotFoundError(f"No cost table at {resolved} — {_REGEN_HINT}.")
    with resolved.open("r") as fh:
        table = yaml.safe_load(fh)
    if not isinstance(table, dict):
        raise ValueError(f"Malformed cost table at {resolved} — {_REGEN_HINT}.")
    logger.debug("Loaded cost table from %s (%d symbols)", resolved, len(table))
    return table


def cost_for(
    symbol: str,
    *,
    stat: str = "half_spread_frac",
    path: str | Path | None = None,
) -> float:
    """Return one cost statistic for ``symbol``, as a fraction of price.

    Parameters
    ----------
    symbol
        Symbol key as written in ``costs.yml`` (e.g. ``"EUR-USD"``).
    stat
        Entry key to read. Defaults to ``half_spread_frac``, the per-fill
        cost to hand to VBT's ``slippage``.
    path
        Optional override of the cost table location.
    """
    table = load_cost_table(path)
    if symbol not in table:
        raise KeyError(
            f"No cost entry for symbol {symbol!r} — known symbols: "
            f"{', '.join(sorted(table))}. If it is a new symbol, "
            f"{_REGEN_HINT}."
        )
    entry = table[symbol]
    if stat not in entry:
        raise KeyError(
            f"No stat {stat!r} for symbol {symbol!r} — available: "
            f"{', '.join(sorted(entry))}."
        )
    return float(entry[stat])
